// Generated by scripts/sync-series-catalog.mjs. Do not edit by hand.
export const LANDING_STORIES = [
  {
    "id": "opening-night",
    "title": "Opening Night",
    "image": "/media/opening-night.jpg",
    "episode": "Episode 1",
    "hook": "Her replacement is already waiting.",
    "votes": "Vote open",
    "tone": "Psychological Thriller · Science Fiction Drama",
    "mediaLabel": "Cold open",
    "runtimeLabel": "30 sec"
  },
  {
    "id": "two-rings-at-the-funeral",
    "title": "Two Rings at the Funeral",
    "image": "/media/two-rings-at-the-funeral.png",
    "episode": "Episode 1",
    "hook": "One coffin. Two wives. No body.",
    "votes": "Vote open",
    "tone": "Romantic Suspense · Revenge Mystery",
    "mediaLabel": "Video teaser",
    "runtimeLabel": "10 sec teaser"
  },
  {
    "id": "crown-of-rust",
    "title": "Crown of Rust",
    "image": "/media/crown-of-rust.jpg",
    "episode": "Episode 1",
    "hook": "The kingdom drowned. Its last knight didn't.",
    "votes": "Vote open",
    "tone": "Fantasy Adventure · Romantic Mystery",
    "mediaLabel": "Video teaser",
    "runtimeLabel": "6 sec teaser"
  },
  {
    "id": "midnight-ramen",
    "title": "Midnight Ramen",
    "image": "/media/midnight-ramen.jpg",
    "episode": "Episode 1",
    "hook": "The letter can open only if Emi is dead.",
    "votes": "Vote open",
    "tone": "Human Drama · Comfort Mystery",
    "mediaLabel": "Video teaser",
    "runtimeLabel": "6 sec teaser"
  },
  {
    "id": "neon-harvest",
    "title": "Neon Harvest",
    "image": "/media/neon-harvest.jpg",
    "episode": "Episode 1",
    "hook": "The stolen seed belongs to her missing mother.",
    "votes": "Vote open",
    "tone": "Science-Fiction Noir · Conspiracy Thriller",
    "mediaLabel": "Video teaser",
    "runtimeLabel": "6 sec teaser"
  },
  {
    "id": "the-last-alibi",
    "title": "The Last Alibi",
    "image": "/media/the-last-alibi.png",
    "episode": "Episode 14",
    "hook": "The signature was hers. The memory wasn’t.",
    "votes": "Vote open",
    "tone": "Murder Mystery · Legal Thriller",
    "mediaLabel": "Story preview",
    "runtimeLabel": "60–90 sec target"
  },
  {
    "id": "borrowed-vows",
    "title": "Borrowed Vows",
    "image": "/media/borrowed-vows.png",
    "episode": "Episode 8",
    "hook": "The bride vanished. Her marriage did not.",
    "votes": "Vote open",
    "tone": "Romance · Comedy Of Errors",
    "mediaLabel": "Story preview",
    "runtimeLabel": "60–90 sec target"
  },
  {
    "id": "the-heir-upstairs",
    "title": "The Heir Upstairs",
    "image": "/media/the-heir-upstairs.png",
    "episode": "Episode 21",
    "hook": "Her new key opened his oldest lie.",
    "votes": "Vote open",
    "tone": "Romantic Suspense · Class Drama",
    "mediaLabel": "Story preview",
    "runtimeLabel": "60–90 sec target"
  }
] as const;
