// Generated by scripts/sync-series-catalog.mjs. Do not edit by hand.
export const LANDING_STORIES = [
  {
    "id": "the-last-alibi",
    "title": "The Last Alibi",
    "image": "/media/the-last-alibi.png",
    "episode": "Episode 14",
    "hook": "The signature was hers. The memory wasn’t.",
    "votes": "18.2K voting",
    "tone": "Murder Mystery · Legal Thriller"
  },
  {
    "id": "borrowed-vows",
    "title": "Borrowed Vows",
    "image": "/media/borrowed-vows.png",
    "episode": "Episode 8",
    "hook": "The bride vanished. Her marriage did not.",
    "votes": "11.7K voting",
    "tone": "Romance · Comedy Of Errors"
  },
  {
    "id": "the-heir-upstairs",
    "title": "The Heir Upstairs",
    "image": "/media/the-heir-upstairs.png",
    "episode": "Episode 21",
    "hook": "Her new key opened his oldest lie.",
    "votes": "24.6K voting",
    "tone": "Romantic Suspense · Class Drama"
  },
  {
    "id": "two-rings-at-the-funeral",
    "title": "Two Rings at the Funeral",
    "image": "/media/two-rings-at-the-funeral.png",
    "episode": "Episode 8",
    "hook": "Celeste tells Mara that the man on the live call is not Elias, just as the caller addresses her by the private name of her unborn child.",
    "votes": "Vote open",
    "tone": "Romantic Suspense · Revenge Mystery"
  }
] as const;
