// Generated by scripts/sync-series-catalog.mjs. Do not edit by hand.
import type { ImageSource } from "expo-image";
import type { VideoSource } from "expo-video";

export type Story = {
  id: string;
  title: string;
  episodeId: string;
  episode: number;
  episodeCount: number;
  episodeTitle: string;
  synopsis: string;
  description: string;
  genres: string;
  poster: ImageSource | string | number;
  videoSource?: VideoSource;
  locked?: boolean;
  vote?: { question: string; choices: readonly string[] };
};

export const STORIES: Story[] = [
  {
    "id": "the-last-alibi",
    "title": "The Last Alibi",
    "episodeId": "the-last-alibi-01",
    "episode": 1,
    "episodeCount": 24,
    "episodeTitle": "Blood in Chambers",
    "synopsis": "Nora wakes beside her murdered mentor as the courthouse locks and her own signed confession prints downstairs.",
    "description": "Nora Vale wakes in a closed courthouse with blood on her sleeve and no memory of the previous hour. Her mentor is dead in chambers, the security archive has been cut, and someone has filed a sealed confession in Nora's name. Hunted by the detective who ended her career, Nora follows courtroom clues that turn every old client into a suspect. The audience decides which testimony she trusts and which dangerous truth becomes canon.",
    "genres": "MURDER MYSTERY · LEGAL THRILLER",
    "vote": {
      "question": "Which clue should Nora pursue before the archive locks?",
      "choices": [
        "Trace the red dress",
        "Test the confession"
      ]
    },
    poster: require("../../assets/images/stories/the-last-alibi.jpg"),
  },
  {
    "id": "borrowed-vows",
    "title": "Borrowed Vows",
    "episodeId": "borrowed-vows-01",
    "episode": 1,
    "episodeCount": 24,
    "episodeTitle": "Bride for Five Minutes",
    "synopsis": "Amara puts on the missing bride's veil to delay a livestream, but Julian turns the stalling tactic into legal vows.",
    "description": "When a celebrity bride vanishes minutes before a globally streamed wedding, planner Amara Lin puts on the veil to stall the sponsors and save her mother's venue from bankruptcy. Groom Julian Reyes recognizes her immediately but completes the vows because his inheritance depends on marrying before sunset. Their improvised bargain should last one hour; instead, a leaked certificate, a trapped wedding party, and the missing bride's voice notes turn the charade into a public marriage. Audience choices decide whether Amara and Julian protect the lie, expose each other, or risk making the borrowed vows sincere.",
    "genres": "ROMANCE · COMEDY OF ERRORS",
    "vote": {
      "question": "How should Amara face the returning livestream?",
      "choices": [
        "Kiss for the cameras",
        "Fake a faint"
      ]
    },
    poster: require("../../assets/images/stories/borrowed-vows.jpg"),
  },
  {
    "id": "the-heir-upstairs",
    "title": "The Heir Upstairs",
    "episodeId": "the-heir-upstairs-01",
    "episode": 1,
    "episodeCount": 24,
    "episodeTitle": "Penthouse Occupied",
    "synopsis": "While documenting an illegal eviction, Leila rides the broken elevator above its final floor and finds the missing heir alive.",
    "description": "Leila Hart has thirty days to stop the Armitage family from evicting everyone in Bellweather House. Then she finds Adrian Armitage hiding in the supposedly empty penthouse, alive after five years and unable to claim his inheritance without a witness who can prove he lived there before his disappearance. Leila agrees to hide him in exchange for ownership protections, but every elevator opens on another family spy, forged deed, or inconvenient spark. The audience chooses which tenant secret becomes leverage and whether Leila trusts the heir upstairs.",
    "genres": "ROMANTIC SUSPENSE · CLASS DRAMA",
    "vote": {
      "question": "What should Leila demand before hiding Adrian?",
      "choices": [
        "Sign the injunction",
        "Explain the signature"
      ]
    },
    poster: require("../../assets/images/stories/the-heir-upstairs.jpg"),
  },
  {
    "id": "two-rings-at-the-funeral",
    "title": "Two Rings at the Funeral",
    "episodeId": "two-rings-at-the-funeral-01",
    "episode": 1,
    "episodeCount": 24,
    "episodeTitle": "The Other Widow",
    "synopsis": "A stranger stops Elias's burial by claiming to be his wife, but matching rings and simultaneous bank thefts turn accusation into a shared emergency.",
    "description": "Paramedic Mara Vega expects grief, not another widow. Celeste Okafor arrives at Elias Vale's funeral with a legal marriage certificate, a baby on the way, and the same numbered ring on her hand. Before either woman can decide who was betrayed first, their bank accounts are emptied and Elias's private ringtone sounds from inside his sealed coffin. Elias's estranged brother Theo warns them to walk away, but Mara and Celeste form an uneasy alliance instead. Each clue reveals that their marriages were components of a larger identity-laundering scheme, while audience choices decide which evidence they chase, which secrets they trade, and whether Theo becomes an ally or the next suspect.",
    "genres": "ROMANTIC SUSPENSE · REVENGE MYSTERY",
    "vote": {
      "question": "Which lead should the widows follow first?",
      "choices": [
        "Open the coffin",
        "Trace the transfer",
        "Follow Theo"
      ]
    },
    poster: require("../../assets/images/stories/two-rings-at-the-funeral.png"),
  }
];
